services:
  backend:
    container_name: backend
    user: root
    build:
      context: .docker/backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www
    tty: true

  database:
    image: postgres:16.3-alpine3.20
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "projectx"
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672
      - 5552:5552
    labels:
      NAME: "echthaar"